# FileSyncHub Configuration Example

# Root directory to monitor for changes
root_dir = "/path/to/your/sync/directory"

# Temporary directory for file operations
temp_dir = "/path/to/temp/directory"

# Plugin configurations
[plugins]

[plugins.onedrive]
enabled = true
root_folder = "FileSyncHub"
credentials_file = "examples/credentials/onedrive_example.json"

[plugins.google_drive]
enabled = true
root_folder = "FileSyncHub"
credentials_file = "examples/credentials/google_drive_example.json"

# Synchronization settings
[sync]
# Debounce time in milliseconds
debounce_time = 2000

# File patterns to ignore
ignore_patterns = ["*.tmp", "*.swp", ".git/*", "node_modules/*"]

# Logging configuration
[logging]
level = "info"
file = "filesynchub.log"
max_size = 10485760      # 10MB
max_files = 5
